[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
puppet_master = "khMMz4PvNMXy3V1E4zvsmk2VRjkvui3bGNeSSDcod5C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
